PROJECT_NAME: RaidenCRUD
PROJECT_ID: axirknptciirtxlhzvgv
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_8f8e5cf5be424565e64ce9af9eca6fcb1bf45bc2
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4aXJrbnB0Y2lpcnR4bGh6dmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTczOTk3NDUsImV4cCI6MjAzMjk3NTc0NX0.K-68F2MjX6ecAOxNFnEFYHlW9SmLZGp0Na1ufthcI-w
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4aXJrbnB0Y2lpcnR4bGh6dmd2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxNzM5OTc0NSwiZXhwIjoyMDMyOTc1NzQ1fQ.CisqqfVyqunYX0TTSOQpivoqyw3ZcIJVOMpbwNi7oFI

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://axirknptciirtxlhzvgv.supabase.co

SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
