PROJECT_NAME: RaidenCRUD
PROJECT_ID: axirknptciirtxlhzvgv
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN:
ANON_KEY: 
SERVICE_KEY: 
SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://axirknptciirtxlhzvgv.supabase.co

# set your ip address to allow access to the database
# example:
# SERVER_HOST: 192.168.18.20
# default is localhost
SERVER_HOST: 172.0.0.1
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
